
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only: latest
    docker:
      # specify the version you desire here
      - image: circleci/node:10.9.0

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}


  # deploy-staging:
  #     docker:
  #       - image: buildpack-deps:trusty
  #     steps:
  #       - checkout
  #       # Download and cache dependencies
  #       - restore_cache:
  #         key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}-{{ .Environment.CIRCLE_SHA1 }}    
         
      - add_ssh_keys:
          fingerprints:
            - "c0:1b:eb:3e:f8:c2:12:9e:ba:fa:0d:f8:63:a2:5f:13"
      - run:
          name: Deploying to staging
          command: ssh -o StrictHostKeyChecking=no -v $DROPLET_USER@$DROPLET_IP "cd /home/payx/app && git pull https://$GITHUB_USER:$GITHUB_PASS@github.com/$GITHUB_USER/PAymenty-X && npm i && pm2 restart 0"

# workflows:
#   version: 2
#   build-deploy:
#     jobs:
#       - build
#       - deploy-staging:
#           requires:
#             - build
#       - approve-prod-deploy:
#           type: approval
#           requires:
#             - build
#           filters:
#             branches:
#               only: staging
#       - deploy-prod:
#           requires:
#             - approve-prod-deploy
#           filters:
#             branches:
#               only: production